// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/active_nav/foo/bar.tsx";
import * as $2 from "./routes/active_nav/foo/index.tsx";
import * as $3 from "./routes/active_nav/index.tsx";
import * as $4 from "./routes/active_nav/island.tsx";
import * as $5 from "./routes/active_nav_partial/_layout.tsx";
import * as $6 from "./routes/active_nav_partial/foo/bar.tsx";
import * as $7 from "./routes/active_nav_partial/foo/index.tsx";
import * as $8 from "./routes/active_nav_partial/index.tsx";
import * as $9 from "./routes/active_nav_partial/island.tsx";
import * as $10 from "./routes/client_nav/_layout.tsx";
import * as $11 from "./routes/client_nav/index.tsx";
import * as $12 from "./routes/client_nav/injected.tsx";
import * as $13 from "./routes/client_nav/page-a.tsx";
import * as $14 from "./routes/client_nav/page-b.tsx";
import * as $15 from "./routes/client_nav/page-c.tsx";
import * as $16 from "./routes/client_nav_opt_out/_layout.tsx";
import * as $17 from "./routes/client_nav_opt_out/index.tsx";
import * as $18 from "./routes/client_nav_opt_out/injected.tsx";
import * as $19 from "./routes/client_nav_opt_out/page-a.tsx";
import * as $20 from "./routes/client_nav_opt_out/page-b.tsx";
import * as $21 from "./routes/client_nav_opt_out/page-c.tsx";
import * as $22 from "./routes/form/index.tsx";
import * as $23 from "./routes/form/injected.tsx";
import * as $24 from "./routes/form/update.tsx";
import * as $25 from "./routes/fragment_nav.tsx";
import * as $26 from "./routes/index.tsx";
import * as $27 from "./routes/island_instance/index.tsx";
import * as $28 from "./routes/island_instance/injected.tsx";
import * as $29 from "./routes/island_instance/partial.tsx";
import * as $30 from "./routes/island_instance/partial_remove.tsx";
import * as $31 from "./routes/island_instance/partial_replace.tsx";
import * as $32 from "./routes/island_instance_multiple/index.tsx";
import * as $33 from "./routes/island_instance_multiple/injected.tsx";
import * as $34 from "./routes/island_instance_multiple/partial.tsx";
import * as $35 from "./routes/island_instance_multiple/partial_both.tsx";
import * as $36 from "./routes/island_instance_nested/index.tsx";
import * as $37 from "./routes/island_instance_nested/injected.tsx";
import * as $38 from "./routes/island_instance_nested/partial.tsx";
import * as $39 from "./routes/island_instance_nested/replace.tsx";
import * as $40 from "./routes/island_props/index.tsx";
import * as $41 from "./routes/island_props/injected.tsx";
import * as $42 from "./routes/island_props/partial.tsx";
import * as $43 from "./routes/island_props_signals/index.tsx";
import * as $44 from "./routes/island_props_signals/injected.tsx";
import * as $45 from "./routes/island_props_signals/partial.tsx";
import * as $46 from "./routes/keys/index.tsx";
import * as $47 from "./routes/keys/injected.tsx";
import * as $48 from "./routes/keys/swap.tsx";
import * as $49 from "./routes/keys_components/index.tsx";
import * as $50 from "./routes/keys_components/injected.tsx";
import * as $51 from "./routes/keys_components/swap.tsx";
import * as $52 from "./routes/keys_dom/index.tsx";
import * as $53 from "./routes/keys_dom/injected.tsx";
import * as $54 from "./routes/keys_dom/swap.tsx";
import * as $55 from "./routes/loading/index.tsx";
import * as $56 from "./routes/loading/injected.tsx";
import * as $57 from "./routes/loading/update.tsx";
import * as $58 from "./routes/missing_partial/index.tsx";
import * as $59 from "./routes/missing_partial/injected.tsx";
import * as $60 from "./routes/missing_partial/update.tsx";
import * as $61 from "./routes/mode/append.tsx";
import * as $62 from "./routes/mode/index.tsx";
import * as $63 from "./routes/mode/injected.tsx";
import * as $64 from "./routes/mode/prepend.tsx";
import * as $65 from "./routes/mode/replace.tsx";
import * as $66 from "./routes/no_islands/index.tsx";
import * as $67 from "./routes/no_islands/injected.tsx";
import * as $68 from "./routes/no_islands/update.tsx";
import * as $69 from "./routes/no_partial_response/index.tsx";
import * as $70 from "./routes/no_partial_response/injected.tsx";
import * as $71 from "./routes/no_partial_response/update.tsx";
import * as $72 from "./routes/partial_slot_inside_island.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/CounterA.tsx";
import * as $$2 from "./islands/CounterB.tsx";
import * as $$3 from "./islands/Fader.tsx";
import * as $$4 from "./islands/InvalidSlot.tsx";
import * as $$5 from "./islands/LazyLink.tsx";
import * as $$6 from "./islands/Logger.tsx";
import * as $$7 from "./islands/Other.tsx";
import * as $$8 from "./islands/PartialTrigger.tsx";
import * as $$9 from "./islands/PassThrough.tsx";
import * as $$10 from "./islands/PropIsland.tsx";
import * as $$11 from "./islands/SignalProp.tsx";
import * as $$12 from "./islands/Spinner.tsx";
import * as $$13 from "./islands/Stateful.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/active_nav/foo/bar.tsx": $1,
    "./routes/active_nav/foo/index.tsx": $2,
    "./routes/active_nav/index.tsx": $3,
    "./routes/active_nav/island.tsx": $4,
    "./routes/active_nav_partial/_layout.tsx": $5,
    "./routes/active_nav_partial/foo/bar.tsx": $6,
    "./routes/active_nav_partial/foo/index.tsx": $7,
    "./routes/active_nav_partial/index.tsx": $8,
    "./routes/active_nav_partial/island.tsx": $9,
    "./routes/client_nav/_layout.tsx": $10,
    "./routes/client_nav/index.tsx": $11,
    "./routes/client_nav/injected.tsx": $12,
    "./routes/client_nav/page-a.tsx": $13,
    "./routes/client_nav/page-b.tsx": $14,
    "./routes/client_nav/page-c.tsx": $15,
    "./routes/client_nav_opt_out/_layout.tsx": $16,
    "./routes/client_nav_opt_out/index.tsx": $17,
    "./routes/client_nav_opt_out/injected.tsx": $18,
    "./routes/client_nav_opt_out/page-a.tsx": $19,
    "./routes/client_nav_opt_out/page-b.tsx": $20,
    "./routes/client_nav_opt_out/page-c.tsx": $21,
    "./routes/form/index.tsx": $22,
    "./routes/form/injected.tsx": $23,
    "./routes/form/update.tsx": $24,
    "./routes/fragment_nav.tsx": $25,
    "./routes/index.tsx": $26,
    "./routes/island_instance/index.tsx": $27,
    "./routes/island_instance/injected.tsx": $28,
    "./routes/island_instance/partial.tsx": $29,
    "./routes/island_instance/partial_remove.tsx": $30,
    "./routes/island_instance/partial_replace.tsx": $31,
    "./routes/island_instance_multiple/index.tsx": $32,
    "./routes/island_instance_multiple/injected.tsx": $33,
    "./routes/island_instance_multiple/partial.tsx": $34,
    "./routes/island_instance_multiple/partial_both.tsx": $35,
    "./routes/island_instance_nested/index.tsx": $36,
    "./routes/island_instance_nested/injected.tsx": $37,
    "./routes/island_instance_nested/partial.tsx": $38,
    "./routes/island_instance_nested/replace.tsx": $39,
    "./routes/island_props/index.tsx": $40,
    "./routes/island_props/injected.tsx": $41,
    "./routes/island_props/partial.tsx": $42,
    "./routes/island_props_signals/index.tsx": $43,
    "./routes/island_props_signals/injected.tsx": $44,
    "./routes/island_props_signals/partial.tsx": $45,
    "./routes/keys/index.tsx": $46,
    "./routes/keys/injected.tsx": $47,
    "./routes/keys/swap.tsx": $48,
    "./routes/keys_components/index.tsx": $49,
    "./routes/keys_components/injected.tsx": $50,
    "./routes/keys_components/swap.tsx": $51,
    "./routes/keys_dom/index.tsx": $52,
    "./routes/keys_dom/injected.tsx": $53,
    "./routes/keys_dom/swap.tsx": $54,
    "./routes/loading/index.tsx": $55,
    "./routes/loading/injected.tsx": $56,
    "./routes/loading/update.tsx": $57,
    "./routes/missing_partial/index.tsx": $58,
    "./routes/missing_partial/injected.tsx": $59,
    "./routes/missing_partial/update.tsx": $60,
    "./routes/mode/append.tsx": $61,
    "./routes/mode/index.tsx": $62,
    "./routes/mode/injected.tsx": $63,
    "./routes/mode/prepend.tsx": $64,
    "./routes/mode/replace.tsx": $65,
    "./routes/no_islands/index.tsx": $66,
    "./routes/no_islands/injected.tsx": $67,
    "./routes/no_islands/update.tsx": $68,
    "./routes/no_partial_response/index.tsx": $69,
    "./routes/no_partial_response/injected.tsx": $70,
    "./routes/no_partial_response/update.tsx": $71,
    "./routes/partial_slot_inside_island.tsx": $72,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/CounterA.tsx": $$1,
    "./islands/CounterB.tsx": $$2,
    "./islands/Fader.tsx": $$3,
    "./islands/InvalidSlot.tsx": $$4,
    "./islands/LazyLink.tsx": $$5,
    "./islands/Logger.tsx": $$6,
    "./islands/Other.tsx": $$7,
    "./islands/PartialTrigger.tsx": $$8,
    "./islands/PassThrough.tsx": $$9,
    "./islands/PropIsland.tsx": $$10,
    "./islands/SignalProp.tsx": $$11,
    "./islands/Spinner.tsx": $$12,
    "./islands/Stateful.tsx": $$13,
  },
  baseUrl: import.meta.url,
};

export default manifest;
