// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/github/auth.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/signin.ts";
import * as $3 from "./routes/signout.ts";
import * as $$0 from "./islands/TodoItem.tsx";

const manifest = {
  routes: {
    "./routes/github/auth.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/signin.ts": $2,
    "./routes/signout.ts": $3,
  },
  islands: {
    "./islands/TodoItem.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
