// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/index.tsx";

const routes = {
  pages: {
    "./pages/index.tsx": $0,
  },
  baseUrl: import.meta.url,
};

export default routes;
