// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/simple_name_conflict/users.ts";
import * as $1 from "./routes/simple_name_conflict/users.tsx";

const manifest = {
  routes: {
    "./routes/simple_name_conflict/users.ts": $0,
    "./routes/simple_name_conflict/users.tsx": $1,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
