[files]
extend-exclude = [
  "packages/core/tests/fixture_partials/routes/scroll_restoration/index.tsx",
  "www/static/fonts/FixelVariable.woff2",
  "www/static/fonts/FixelVariableItalic.woff2",
  "packages/core/tests/lorem_ipsum.txt",
]

[default]
extend-ignore-identifiers-re = ["Fixel"]
