// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/evil.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/islands/index.tsx";
import * as $$0 from "../shared_islands/Test.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/kebab_test/kebab-case-counter-test.tsx";
import * as $$3 from "https://deno.land/x/fresh@1.1.2/tests/fixture/islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/evil.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/islands/index.tsx": $2,
  },
  islands: {
    "../shared_islands/Test.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/kebab_test/kebab-case-counter-test.tsx": $$2,
    "https://deno.land/x/fresh@1.1.2/tests/fixture/islands/Counter.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
