// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh generate`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./partials/Counter.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
  },
  partials: {
    "./partials/Counter.tsx": $1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
