// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/action_island.tsx";
import * as $1 from "./routes/action_lifecycle.tsx";
import * as $2 from "./routes/action_server.tsx";
import * as $3 from "./routes/action_slot.tsx";
import * as $4 from "./routes/action_slot_multiple.tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/ActionIsland.tsx";
import * as $$1 from "./islands/ActionSlot.tsx";
import * as $$$0 from "./actions/hello.ts";
import * as $$$1 from "./actions/hello2.ts";
import * as $$$2 from "./actions/lifecycle.ts";
import * as $$$3 from "./actions/multi_1.ts";
import * as $$$4 from "./actions/multi_2.ts";

const manifest = {
  routes: {
    "./routes/action_island.tsx": $0,
    "./routes/action_lifecycle.tsx": $1,
    "./routes/action_server.tsx": $2,
    "./routes/action_slot.tsx": $3,
    "./routes/action_slot_multiple.tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/ActionIsland.tsx": $$0,
    "./islands/ActionSlot.tsx": $$1,
  },
  actions: {
    "./actions/hello.ts": $$$0,
    "./actions/hello2.ts": $$$1,
    "./actions/lifecycle.ts": $$$2,
    "./actions/multi_1.ts": $$$3,
    "./actions/multi_2.ts": $$$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
