// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/basic.tsx";
import * as $1 from "./routes/context/[id].tsx";
import * as $2 from "./routes/fail.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/island.tsx";
import * as $5 from "./routes/response.tsx";
import * as $6 from "./routes/twind.tsx";
import * as $$0 from "./islands/FooIsland.tsx";

const manifest = {
  routes: {
    "./routes/basic.tsx": $0,
    "./routes/context/[id].tsx": $1,
    "./routes/fail.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/island.tsx": $4,
    "./routes/response.tsx": $5,
    "./routes/twind.tsx": $6,
  },
  islands: {
    "./islands/FooIsland.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
