// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/basic.tsx": await import("./routes/basic.tsx"),
    "./routes/context/[id].tsx": await import("./routes/context/[id].tsx"),
    "./routes/fail.tsx": await import("./routes/fail.tsx"),
    "./routes/index.tsx": await import("./routes/index.tsx"),
    "./routes/island.tsx": await import("./routes/island.tsx"),
    "./routes/response.tsx": await import("./routes/response.tsx"),
    "./routes/twind.tsx": await import("./routes/twind.tsx"),
  },
  islands: {
    "./islands/FooIsland.tsx": await import("./islands/FooIsland.tsx"),
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
