// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/sub-route/index.tsx";
import * as $$0 from "../fixture/islands/Counter.tsx";
import * as $$1 from "https://deno.land/x/fresh@1.5.2/tests/fixture/islands/Counter.tsx";
import * as $$2 from "https://deno.land/x/fresh@1.5.2/tests/fixture/islands/folder/Counter.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/sub-route/index.tsx": $1,
  },
  islands: {
    "../fixture/islands/Counter.tsx": $$0,
    "https://deno.land/x/fresh@1.5.2/tests/fixture/islands/Counter.tsx": $$1,
    "https://deno.land/x/fresh@1.5.2/tests/fixture/islands/folder/Counter.tsx":
      $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
