// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": await import("./routes/_app.tsx"),
    "./routes/_layout.tsx": await import("./routes/_layout.tsx"),
    "./routes/index.tsx": await import("./routes/index.tsx"),
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
