// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404_from_middleware_middleware from "./routes/404-from-middleware/_middleware.ts";
import * as $_404_from_middleware_index from "./routes/404-from-middleware/index.tsx";
import * as $_404 from "./routes/_404.tsx";

import { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/404-from-middleware/_middleware.ts":
      $_404_from_middleware_middleware,
    "./routes/404-from-middleware/index.tsx": $_404_from_middleware_index,
    "./routes/_404.tsx": $_404,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
