// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $index from "./routes/index.tsx";
import * as $Multiple from "./islands/Multiple.tsx";
import * as $MultipleDefault from "./islands/MultipleDefault.tsx";
import * as $Single from "./islands/Single.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Multiple.tsx": $Multiple,
    "./islands/MultipleDefault.tsx": $MultipleDefault,
    "./islands/Single.tsx": $Single,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
