// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/docs/[...slug].tsx";
import * as $2 from "./routes/gfm.css.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/level1/level2/[test].tsx";
import * as $5 from "./routes/level1/level2/test.tsx";
import * as $6 from "./routes/raw.ts";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/LemonDrop.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/docs/[...slug].tsx": $1,
    "./routes/gfm.css.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/level1/level2/[test].tsx": $4,
    "./routes/level1/level2/test.tsx": $5,
    "./routes/raw.ts": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/LemonDrop.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
