// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": await import("./routes/_404.tsx"),
    "./routes/_500.tsx": await import("./routes/_500.tsx"),
    "./routes/_app.tsx": await import("./routes/_app.tsx"),
    "./routes/_middleware.ts": await import("./routes/_middleware.ts"),
    "./routes/components.tsx": await import("./routes/components.tsx"),
    "./routes/docs/[...slug].tsx": await import("./routes/docs/[...slug].tsx"),
    "./routes/docs/_middleware.ts": await import(
      "./routes/docs/_middleware.ts"
    ),
    "./routes/docs/index.tsx": await import("./routes/docs/index.tsx"),
    "./routes/index.tsx": await import("./routes/index.tsx"),
    "./routes/raw.ts": await import("./routes/raw.ts"),
    "./routes/showcase.tsx": await import("./routes/showcase.tsx"),
    "./routes/update.tsx": await import("./routes/update.tsx"),
  },
  islands: {
    "./islands/ComponentGallery.tsx": await import(
      "./islands/ComponentGallery.tsx"
    ),
    "./islands/CopyArea.tsx": await import("./islands/CopyArea.tsx"),
    "./islands/Counter.tsx": await import("./islands/Counter.tsx"),
    "./islands/LemonDrop.tsx": await import("./islands/LemonDrop.tsx"),
    "./islands/SearchButton.tsx": await import("./islands/SearchButton.tsx"),
    "./islands/TableOfContents.tsx": await import(
      "./islands/TableOfContents.tsx"
    ),
    "./islands/VersionSelect.tsx": await import("./islands/VersionSelect.tsx"),
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
