// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/index.tsx";
import * as $1 from "./pages/_render.ts";

const routes = {
  pages: {
    "./pages/index.tsx": $0,
    "./pages/_render.ts": $1,
  },
  baseUrl: import.meta.url,
};

export default routes;
