// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/conflicts/:id.tsx";
import * as $2 from "./routes/custom.txt.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/nested/_app.tsx";
import * as $5 from "./routes/test.tsx";
import * as $6 from "./routes/test/index.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/conflicts/:id.tsx": $1,
    "./routes/custom.txt.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/nested/_app.tsx": $4,
    "./routes/test.tsx": $5,
    "./routes/test/index.tsx": $6,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
