// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/evil.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/islands/index.tsx";
import * as $$0 from "./routes/islands/Counter.island.tsx";
import * as $$1 from "./routes/islands/Test.island.tsx";
import * as $$2 from "./routes/islands/kebab-case-counter-test.island.tsx";

const manifest = {
  routes: {
    "./routes/evil.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/islands/index.tsx": $2,
  },
  islands: {
    "./routes/islands/Counter.island.tsx": $$0,
    "./routes/islands/Test.island.tsx": $$1,
    "./routes/islands/kebab-case-counter-test.island.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
