// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/header_arr.tsx";
import * as $1 from "./routes/header_instance.tsx";
import * as $2 from "./routes/header_obj.tsx";
import * as $3 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/header_arr.tsx": $0,
    "./routes/header_instance.tsx": $1,
    "./routes/header_obj.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
