// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/head_style.tsx": await import("./routes/head_style.tsx"),
    "./routes/header_arr.tsx": await import("./routes/header_arr.tsx"),
    "./routes/header_instance.tsx": await import(
      "./routes/header_instance.tsx"
    ),
    "./routes/header_obj.tsx": await import("./routes/header_obj.tsx"),
    "./routes/index.tsx": await import("./routes/index.tsx"),
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
