// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_layout.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/files/js/_layout.js";
import * as $4 from "./routes/files/js/index.js";
import * as $5 from "./routes/files/jsx/_layout.jsx";
import * as $6 from "./routes/files/jsx/index.jsx";
import * as $7 from "./routes/files/ts/_layout.ts";
import * as $8 from "./routes/files/ts/index.ts";
import * as $9 from "./routes/files/tsx/_layout.tsx";
import * as $10 from "./routes/files/tsx/index.tsx";
import * as $11 from "./routes/foo/_layout.tsx";
import * as $12 from "./routes/foo/bar.tsx";
import * as $13 from "./routes/foo/index.tsx";
import * as $14 from "./routes/index.tsx";
import * as $15 from "./routes/other.tsx";
import * as $16 from "./routes/skip/sub/_layout.tsx";
import * as $17 from "./routes/skip/sub/index.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_layout.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/files/js/_layout.js": $3,
    "./routes/files/js/index.js": $4,
    "./routes/files/jsx/_layout.jsx": $5,
    "./routes/files/jsx/index.jsx": $6,
    "./routes/files/ts/_layout.ts": $7,
    "./routes/files/ts/index.ts": $8,
    "./routes/files/tsx/_layout.tsx": $9,
    "./routes/files/tsx/index.tsx": $10,
    "./routes/foo/_layout.tsx": $11,
    "./routes/foo/bar.tsx": $12,
    "./routes/foo/index.tsx": $13,
    "./routes/index.tsx": $14,
    "./routes/other.tsx": $15,
    "./routes/skip/sub/_layout.tsx": $16,
    "./routes/skip/sub/index.tsx": $17,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
