// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_all_ from "./routes/[...all].ts";
import * as $index from "./routes/index.tsx";

import { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...all].ts": $_all_,
    "./routes/index.tsx": $index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
