// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/[...all].ts";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/[...all].ts": $1,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
