// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_group_index from "./routes/(group)/index.tsx";

const manifest = {
  routes: {
    "./routes/(group)/index.tsx": $_group_index,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
