// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/control/index.tsx";
import * as $1 from "./routes/control/normal_route.tsx";
import * as $2 from "./routes/one_dynamic/[dynamic].tsx";
import * as $3 from "./routes/one_dynamic/normal_route.tsx";
import * as $4 from "./routes/override/normal_route.tsx";
import * as $5 from "./routes/override/override.tsx";

const manifest = {
  routes: {
    "./routes/control/index.tsx": $0,
    "./routes/control/normal_route.tsx": $1,
    "./routes/one_dynamic/[dynamic].tsx": $2,
    "./routes/one_dynamic/normal_route.tsx": $3,
    "./routes/override/normal_route.tsx": $4,
    "./routes/override/override.tsx": $5,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
