// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

const manifest = {
  routes: {
    "./routes/index.tsx": await import("./routes/index.tsx"),
  },
  islands: {
    "./islands/Counter.tsx": await import("./islands/Counter.tsx"),
  },
  baseUrl: import.meta.url,
};

export default manifest;
