// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $index from "./routes/index.tsx";
import * as $passthrough from "./routes/passthrough.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Passthrough from "./islands/Passthrough.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/index.tsx": $index,
    "./routes/passthrough.tsx": $passthrough,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Passthrough.tsx": $Passthrough,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
