// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/passthrough.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Passthrough.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/passthrough.tsx": $1,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Passthrough.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
