export interface RouteConfig {
  /**
   * A route override for the page. This is useful for pages where the route
   * can not be expressed through the filesystem routing capabilities.
   *
   * The route override must be a path-to-regexp compatible route matcher.
   */
  routeOverride?: string;

  /**
   * If Content-Security-Policy should be enabled for this page. If 'true', a
   * locked down policy will be used that allows only the scripts and styles
   * that are generated by Fresh. Additional scripts and styles can be added
   * using the `useCSP` hook.
   */
  csp?: boolean;

  /**
   * Skip already inherited layouts
   * Default: `false`
   */
  skipInheritedLayouts?: boolean;

  /**
   * Skip rendering the `routes/_app` template
   * Default: `false`
   */
  skipAppWrapper?: boolean;
}

export interface SignalLike<T> {
  value: T;
  peek(): T;
  subscribe(fn: (value: T) => void): () => void;
}

declare global {
  namespace preact.createElement.JSX {
    interface HTMLAttributes {
      /**
       * Alternative url to fetch partials from on `<a>` or `<form>` tags
       */
      "f-partial"?: string | SignalLike<string>;
      /**
       * Enable or disable client side navigation and partials for this
       * particular node and its children.
       */
      "f-client-nav"?: boolean | SignalLike<boolean>;
    }
  }
}
