// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_middleware from "./routes/_middleware.ts";
import * as $a_b_b from "./routes/a/b/b.tsx";
import * as $a_b_relative_index from "./routes/a/b/relative/index.tsx";
import * as $api_base_handler from "./routes/api/base-handler.ts";
import * as $api_index from "./routes/api/index.ts";
import * as $api_rewrite from "./routes/api/rewrite.ts";
import * as $baz_slug_ from "./routes/baz/[...slug].tsx";
import * as $codeframe from "./routes/codeframe.tsx";
import * as $error_boundary from "./routes/error_boundary.tsx";
import * as $html from "./routes/html.tsx";
import * as $index from "./routes/index.tsx";
import * as $islands from "./routes/islands.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $_middleware,
    "./routes/a/b/b.tsx": $a_b_b,
    "./routes/a/b/relative/index.tsx": $a_b_relative_index,
    "./routes/api/base-handler.ts": $api_base_handler,
    "./routes/api/index.ts": $api_index,
    "./routes/api/rewrite.ts": $api_rewrite,
    "./routes/baz/[...slug].tsx": $baz_slug_,
    "./routes/codeframe.tsx": $codeframe,
    "./routes/error_boundary.tsx": $error_boundary,
    "./routes/html.tsx": $html,
    "./routes/index.tsx": $index,
    "./routes/islands.tsx": $islands,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
