// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/a/b/b.tsx";
import * as $2 from "./routes/a/b/relative/index.tsx";
import * as $3 from "./routes/api/base-handler.ts";
import * as $4 from "./routes/api/index.ts";
import * as $5 from "./routes/api/rewrite.ts";
import * as $6 from "./routes/baz/[...slug].tsx";
import * as $7 from "./routes/html.tsx";
import * as $8 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/a/b/b.tsx": $1,
    "./routes/a/b/relative/index.tsx": $2,
    "./routes/api/base-handler.ts": $3,
    "./routes/api/index.ts": $4,
    "./routes/api/rewrite.ts": $5,
    "./routes/baz/[...slug].tsx": $6,
    "./routes/html.tsx": $7,
    "./routes/index.tsx": $8,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
