// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_middleware.ts": await import("./routes/_middleware.ts"),
    "./routes/a/b/b.tsx": await import("./routes/a/b/b.tsx"),
    "./routes/a/b/relative/index.tsx": await import(
      "./routes/a/b/relative/index.tsx"
    ),
    "./routes/api/base-handler.ts": await import(
      "./routes/api/base-handler.ts"
    ),
    "./routes/api/index.ts": await import("./routes/api/index.ts"),
    "./routes/api/rewrite.ts": await import("./routes/api/rewrite.ts"),
    "./routes/baz/[...slug].tsx": await import("./routes/baz/[...slug].tsx"),
    "./routes/codeframe.tsx": await import("./routes/codeframe.tsx"),
    "./routes/error_boundary.tsx": await import("./routes/error_boundary.tsx"),
    "./routes/html.tsx": await import("./routes/html.tsx"),
    "./routes/index.tsx": await import("./routes/index.tsx"),
    "./routes/islands.tsx": await import("./routes/islands.tsx"),
  },
  islands: {
    "./islands/Counter.tsx": await import("./islands/Counter.tsx"),
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
