// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/check-duplication.tsx";
import * as $1 from "./routes/insert-cssrules.tsx";
import * as $2 from "./routes/island_twind/_layout.tsx";
import * as $3 from "./routes/island_twind/blue.tsx";
import * as $4 from "./routes/island_twind/index.tsx";
import * as $5 from "./routes/static.tsx";
import * as $6 from "./routes/unused.tsx";
import * as $7 from "./routes/unused_tw.tsx";
import * as $$0 from "./islands/CheckDuplication.tsx";
import * as $$1 from "./islands/InsertCssrules.tsx";
import { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/check-duplication.tsx": $0,
    "./routes/insert-cssrules.tsx": $1,
    "./routes/island_twind/_layout.tsx": $2,
    "./routes/island_twind/blue.tsx": $3,
    "./routes/island_twind/index.tsx": $4,
    "./routes/static.tsx": $5,
    "./routes/unused.tsx": $6,
    "./routes/unused_tw.tsx": $7,
  },
  islands: {
    "./islands/CheckDuplication.tsx": $$0,
    "./islands/InsertCssrules.tsx": $$1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
