// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $check_duplication from "./routes/check-duplication.tsx";
import * as $insert_cssrules from "./routes/insert-cssrules.tsx";
import * as $static from "./routes/static.tsx";
import * as $unused from "./routes/unused.tsx";
import * as $unused_tw from "./routes/unused_tw.tsx";
import * as $$CheckDuplication from "./islands/CheckDuplication.tsx";
import * as $$InsertCssrules from "./islands/InsertCssrules.tsx";

const manifest = {
  routes: {
    "./routes/check-duplication.tsx": $check_duplication,
    "./routes/insert-cssrules.tsx": $insert_cssrules,
    "./routes/static.tsx": $static,
    "./routes/unused.tsx": $unused,
    "./routes/unused_tw.tsx": $unused_tw,
  },
  islands: {
    "./islands/CheckDuplication.tsx": $$CheckDuplication,
    "./islands/InsertCssrules.tsx": $$InsertCssrules,
  },
  baseUrl: import.meta.url,
};

export default manifest;
