// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/check-duplication.tsx";
import * as $1 from "./routes/insert-cssrules.tsx";
import * as $2 from "./routes/static.tsx";
import * as $$0 from "./islands/CheckDuplication.tsx";
import * as $$1 from "./islands/InsertCssrules.tsx";

const manifest = {
  routes: {
    "./routes/check-duplication.tsx": $0,
    "./routes/insert-cssrules.tsx": $1,
    "./routes/static.tsx": $2,
  },
  islands: {
    "./islands/CheckDuplication.tsx": $$0,
    "./islands/InsertCssrules.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
