// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/island_conditional.tsx";
import * as $2 from "./routes/island_in_island.tsx";
import * as $3 from "./routes/island_in_island_definition.tsx";
import * as $4 from "./routes/island_jsx_child.tsx";
import * as $5 from "./routes/island_jsx_children.tsx";
import * as $6 from "./routes/island_jsx_island_jsx.tsx";
import * as $7 from "./routes/island_jsx_text.tsx";
import * as $8 from "./routes/island_nested_props.tsx";
import * as $9 from "./routes/island_siblings.tsx";
import * as $$0 from "./islands/BooleanButton.tsx";
import * as $$1 from "./islands/Island.tsx";
import * as $$2 from "./islands/IslandConditional.tsx";
import * as $$3 from "./islands/IslandInsideIsland.tsx";
import * as $$4 from "./islands/IslandWithProps.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/island_conditional.tsx": $1,
    "./routes/island_in_island.tsx": $2,
    "./routes/island_in_island_definition.tsx": $3,
    "./routes/island_jsx_child.tsx": $4,
    "./routes/island_jsx_children.tsx": $5,
    "./routes/island_jsx_island_jsx.tsx": $6,
    "./routes/island_jsx_text.tsx": $7,
    "./routes/island_nested_props.tsx": $8,
    "./routes/island_siblings.tsx": $9,
  },
  islands: {
    "./islands/BooleanButton.tsx": $$0,
    "./islands/Island.tsx": $$1,
    "./islands/IslandConditional.tsx": $$2,
    "./islands/IslandInsideIsland.tsx": $$3,
    "./islands/IslandWithProps.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
