// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/lots-of-middleware/index.tsx": await import(
      "./routes/lots-of-middleware/index.tsx"
    ),
    "./routes/static.tsx": await import("./routes/static.tsx"),
    "./routes/test.tsx": await import("./routes/test.tsx"),
    "./routes/with-island.tsx": await import("./routes/with-island.tsx"),
  },
  islands: {
    "./islands/Island.tsx": await import("./islands/Island.tsx"),
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
