// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/index.tsx": await import("./routes/index.tsx"),
    "./routes/island.tsx": await import("./routes/island.tsx"),
    "./routes/no_island.tsx": await import("./routes/no_island.tsx"),
  },
  islands: {
    "./islands/Counter.tsx": await import("./islands/Counter.tsx"),
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
