name: post_publish

on:
  release:
    types: [published]

jobs:
  update-dl-version:
    name: update dl.deno.land version
    runs-on: ubuntu-22.04
    if: github.repository == 'denoland/fresh'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Upload version file to dl.deno.land
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: ${{ vars.S3_ENDPOINT }}
          AWS_DEFAULT_REGION: ${{ vars.S3_REGION }}
        run: |
          cat packages/fresh/deno.json | jq -r ".version" > release-latest.txt
          aws s3 cp release-latest.txt s3://dl-deno-land/fresh/release-latest.txt --cache-control "no-cache"
